export const longData = {
    skillNames: [
        "Ja",
        "Jav",
        "Java",
        "Javas",
        "Javasc",
        "Javascr",
        "Javascri",
        "Javascrip",
        "Javascript",
        "Javascrip",
        "Javascri",
        "Javascr",
        "Javasc",
        "Javas",
        "Java",
        "Jav",
        "Ja",
        "J",
        "T",
        "Ty",
        "Typ",
        "Type",
        "Types",
        "Typesc",
        "Typescr",
        "Typescri",
        "Typescrip",
        "Typescript",
        "Typescrip",
        "Typescri",
        "Typescr",
        "Typesc",
        "Types",
        "Type",
        "Typ",
        "Ty",
        "T",
        "H",
        "HT",
        "HTM",
        "HTML",
        "HTML5",
        "HTML",
        "HTM",
        "HT",
        "H",
        "C",
        "CS",
        "CSS",
        "CSS3",
        "CSS",
        "CS",
        "C",
        "R",
        "Re",
        "Rea",
        "Reac",
        "React",
        "ReactJ",
        "ReactJS",
        "ReactJ",
        "React",
        "React ",
        "React N",
        "React Na",
        "React Nat",
        "React Nati",
        "React Nativ",
        "React Native",
        "React Nativ",
        "React Nati",
        "React Nat",
        "React Na",
        "React N",
        "React",
        "Reac",
        "Rea",
        "Re",
        "R",
        "N",
        "No",
        "Nod",
        "Node",
        "NodeJ",
        "NodeJS",
        "NodeJ",
        "Node",
        "Nod",
        "No",
        "N",
        "M",
        "Mo",
        "Mon",
        "Mong",
        "Mongo",
        "MongoD",
        "MongoDB",
        "MongoD",
        "Mongo",
        "Mong",
        "Mon",
        "Mo",
        "M",
        "P",
        "Ph",
        "Pha",
        "Phas",
        "Phase",
        "Phaser",
        "Phaser 3",
        "Phaser",
        "Phase",
        "Phas",
        "Pha",
        "Ph",
        "Py",
        "Pyt",
        "Pyth",
        "Pytho",
        "Python",
        "Pytho",
        "Pyth",
        "Pyt",
        "Py",
        "P",
    ],
};

export const skillData = {
    js: "javascript",
    ts: "typescript",
    reactJS: "reactJS",
    html: "HTML5",
    css: "CSS3",
    reactNative: "React Native",
    node: "NodeJS",
    mongo: "MongoDB",
    phaser: "Phaser 3",
    py: "Python",
};
